---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix-tls
  namespace: matrix
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: matrix-tls
  dnsNames:
    - shaman007.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
