---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: matrix
  name: matrix-lh
  labels:
    storage.k8s.io/name: longhorn
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-b: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: '10Gi'
