---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config-synapse
  namespace: matrix
  labels:
    tier: matrix
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: config-synapse
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server_name: "shaman007.com"
          public_baseurl: "https://shaman007.com"
          data_dir: /data
          signing_key_path: /data/shaman007.com.signing.key
          media_store_path: /data/media_store
          uploads_path: /data/uploads
          pid_file: /data/homeserver.pid

          enable_registration: false
          enable_registration_without_verification: false
          #registration:
          #  enabled: true
          #  registration_requires_token: false
          #  enable_registration_without_verification: true

          #registration_shared_secret: "{{ .registration_shared_secret }}"
          allow_public_rooms_over_federation: true
          enable_metrics: true
          threepid_behaviour_email: local

          email:
            smtp_host: "{{ .smtp_host }}"
            smtp_port: 25
            require_transport_security: false
            notif_from: "{{ .smtp_from }}"
            app_name: "shaman007 Matrix"
            enable_notifs: false

          experimental_features:
            # Reviewed 2026-03-04: keep only actively used flags.
            msc2815_enabled: true
            msc3391_enabled: true
          trusted_key_servers:
            - server_name: "matrix.org"

          listeners:
            - port: 6167
              bind_addresses: ["0.0.0.0"]
              type: http
              tls: false
              x_forwarded: true
              resources:
                - names: [client, federation]
            - port: 8008
              tls: false
              type: http
              x_forwarded: true
              bind_addresses: ['0.0.0.0']
              resources:
                - names: [metrics]

          database:
            name: sqlite3
            args:
              database: /data/homeserver.db

          macaroon_secret_key: "{{ .macaroon_secret_key }}"
          form_secret: "{{ .form_secret }}"
          report_stats: false

          app_service_config_files: []

          loggers:
            synapse.storage:
              level: DEBUG
            synapse.handlers.device:
              level: DEBUG
            synapse.crypto:
              level: DEBUG
  data:
    - secretKey: registration_shared_secret
      remoteRef:
        key: synapse
        property: registration_shared_secret
    - secretKey: macaroon_secret_key
      remoteRef:
        key: synapse
        property: macaroon_secret_key
    - secretKey: form_secret
      remoteRef:
        key: synapse
        property: form_secret
    - secretKey: smtp_host
      remoteRef:
        key: synapse
        property: smtp_host
    - secretKey: smtp_from
      remoteRef:
        key: synapse
        property: smtp_from
