---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-indexer-certs
  namespace: wazuh
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: indexer-certs
    creationPolicy: Owner
  data:
    - secretKey: root-ca.pem
      remoteRef:
        key: wazuh
        property: root_ca_pem
    - secretKey: node.pem
      remoteRef:
        key: wazuh
        property: node_pem
    - secretKey: node-key.pem
      remoteRef:
        key: wazuh
        property: node_key_pem
    - secretKey: admin.pem
      remoteRef:
        key: wazuh
        property: admin_pem
    - secretKey: admin-key.pem
      remoteRef:
        key: wazuh
        property: admin_key_pem
    - secretKey: filebeat.pem
      remoteRef:
        key: wazuh
        property: filebeat_pem
    - secretKey: filebeat-key.pem
      remoteRef:
        key: wazuh
        property: filebeat_key_pem
    - secretKey: dashboard.pem
      remoteRef:
        key: wazuh
        property: dashboard_pem
    - secretKey: dashboard-key.pem
      remoteRef:
        key: wazuh
        property: dashboard_key_pem
