---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-indexer-credentials
  namespace: wazuh
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: indexer-cred
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wazuh
        property: indexer_username
    - secretKey: password
      remoteRef:
        key: wazuh
        property: indexer_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-dashboard-credentials
  namespace: wazuh
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: dashboard-cred
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wazuh
        property: dashboard_username
    - secretKey: password
      remoteRef:
        key: wazuh
        property: dashboard_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-api-credentials
  namespace: wazuh
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: wazuh-api-cred
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wazuh
        property: wazuh_api_username
    - secretKey: password
      remoteRef:
        key: wazuh
        property: wazuh_api_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-authd-password
  namespace: wazuh
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: wazuh-authd-pass
    creationPolicy: Owner
  data:
    - secretKey: authd.pass
      remoteRef:
        key: wazuh
        property: authd_pass
