---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: wazuh
type: Opaque
data:
  # Placeholder token. The vault-token-rotator replaces this with a real token
  # based on the SecretStore policy annotation in this namespace.
  token: ZHVtbXk=
