---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-syslog
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: LoadBalancer
  loadBalancerClass: metallb-l2
  externalTrafficPolicy: Local
  selector:
    app: wazuh-manager
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 514
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 514
      protocol: TCP
