apiVersion: v1
kind: Namespace
metadata:
  name: lenka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lenka-admin
  namespace: lenka
subjects:
  - kind: User
    name: lenka
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
