apiVersion: v1
kind: Service
metadata:
  name: hypermind
  namespace: hypermind
  labels:
    app.kubernetes.io/name: hypermind
    app.kubernetes.io/instance: hypermind
spec:
  type: ClusterIP
  selector:
    app: hypermind
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
