apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "v1.15.0"
    app.kubernetes.io/managed-by: argoCD
