---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-ingress-vault-acme-tls
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: openbao-ingress-vault-acme-tls
  duration: 720h
  renewBefore: 168h
  dnsNames:
    - openbao.w386.k8s.my.lan
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-acme
