---
apiVersion: v1
kind: Secret
metadata:
  name: openbao-server-tls
  namespace: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
type: Opaque
data: {}
