---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: grafana-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: grafana
        property: OIDC_CLIENT_SECRET
