apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: plex-lib
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: local-storage
  selector:
    matchLabels:
      app: plex
      storage-role: plex-media
  resources:
    requests:
      storage: 15Ti
