apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: plex-conf-lh2
  labels:
    storage.k8s.io/name: longhorn
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup-daily-retain31-b: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
