apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app: headlamp
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
        app.kubernetes.io/name: headlamp
        app.kubernetes.io/instance: headlamp
    spec:
      priorityClassName: homelab-standard
      enableServiceLinks: false
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: harbor.andreybondarenko.com/github/headlamp-k8s/headlamp:v0.43.0
          imagePullPolicy: IfNotPresent
          args:
            - -in-cluster
            - -plugins-dir=/headlamp/plugins
          ports:
            - name: http
              containerPort: 4466
            - name: metrics
              containerPort: 9090
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              memory: 128Mi
