---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-requests
  namespace: headlamp
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 128Mi
