apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: headlamp-allow-egress-oidc
  namespace: headlamp
spec:
  podSelector:
    matchLabels:
      app: headlamp
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
