---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: unifi
spec:
  refreshInterval: 900
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVTGRYTUltck1FVVIzSmhCMFdxWWsvMHlqWjBzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF4TVFkek00TmlCTVlXSWdVbTl2ZENCRFFUQWVGdzB5TlRFeE1qQXhOekUxTURCYQpGdzB6TlRFeE1UZ3hOekUxTXpCYU1Cc3hHVEFYQmdOVkJBTVRFSGN6T0RZZ1RHRmlJRkp2YjNRZ1EwRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQy8rM1I5QnIvbTQzZWJZWm1Nb3lMcTBhdkUKbzRXbTZpQTFoNkVIYjZlZ2hpdUtFSGFlcHpmeFgwK3djNzB1UERNUVZBWnA2SFVhKzdSNVB5VEJhNWp4OUgxTQp1NjZxeWlMWHdVU01TMGptQ2tFMUtoblk4Ny9nc1YwRHF4MmYwbWtnVGRWc0h3cEM0QzBWNVdEWXA0M0RvZkJ1Cm9BOWxUN0NRejZIR0FpRkFweHQ1UFdhQlBLN2JVOE83anNUWVg0VTh5WGQyYTlkZE92M09iUlBEUCtSTlZscmQKeXlDTEp0RjkvY3FCb2FENzJqMlYzU2tDVU9Wdm9IMmxHZisrdXV5aXhIWlBtOUw0MDYyc3oxMTNlR1NrK3IvcwpCRXdkNFVON25paHVlVjkxYk9PcDRxdE52YmZmTHR3d3pEcnVjbVAxTllwcC9LQzBoMTVzcFFhSGhqUXpBZ01CCkFBR2pZekJoTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSREoxMlhVdUp4UURTUWJwWGoxVDdyeUNiY0NEQWZCZ05WSFNNRUdEQVdnQlJESjEyWFV1SnhRRFNRYnBYagoxVDdyeUNiY0NEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFL25TTmkzZVNxOGR3dHJKaVJTMExDRlB3SkJHCmNuR25Ta3dacFNaRjVKZFpNVjk4QU1ZTzdJV3J5NGhLZlUrYkZhbDB1U0Y2d0lxZ1R5blVuYm5vbnB2RytoazkKNzlvYjY2TnFSTU5UNTRNd3NvOVIyQUQwSlJYUm9EMWdBOUZybmRMeW1NeDd1bnViSUUvMmtDY2RtV2ZrTTdSUQpkTkhYVEVjdWRZRWlvSjZQY1NpdU5VdHdMZTcrZFQxUGk0QWR6MktMc2NXSmNMWHRzS2t5eW5hQVkwK2xTOWNpCkoyTkZwUytMdzU3QS9lZThBdEpSdEJ4Q0xhN2xpUXhscVRDL29HS0tIQnloNXJUeTNKcVRhenptNVZ6dndvTysKOGtyd0ZPZEhQQVc5dThlU1M2ZTVSZi85VG1vOUJqaUxPNHZtNXVZZkd6azJOQ1g2U1JoL2gxLzE3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-unifi
          serviceAccountRef:
            name: vault-auth
            audiences:
              - vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: unifi
automountServiceAccountToken: false
