---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ferretdb-credentials
  namespace: spotify
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: ferretdb-credentials
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        postgresql-url: "postgres://{{ .username }}:{{ .password }}@ferretdb-postgres.spotify.svc.cluster.local:5432/postgres"
        mongodb-url: "mongodb://{{ .username }}:{{ .password }}@ferretdb.spotify.svc.cluster.local:27017/your_spotify?authSource=postgres"
  data:
    - secretKey: username
      remoteRef:
        key: spotify
        property: FERRETDB_USERNAME
    - secretKey: password
      remoteRef:
        key: spotify
        property: FERRETDB_PASSWORD
