apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-adapter-default-deny
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: my-adapter
      app.kubernetes.io/name: prometheus-adapter
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-adapter-allow-required-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: my-adapter
      app.kubernetes.io/name: prometheus-adapter
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 6443
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app: thanos-querier
      ports:
        - protocol: TCP
          port: 9090
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prometheus-adapter-allow-kube-apiserver
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: my-adapter
      app.kubernetes.io/name: prometheus-adapter
  egress:
    - toEntities:
        - kube-apiserver
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
