apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hister
  namespace: hister
  labels:
    app: hister
    app.kubernetes.io/instance: hister
    app.kubernetes.io/name: hister
    app.kubernetes.io/managed-by: argoCD
spec:
  serviceName: hister
  replicas: 1
  selector:
    matchLabels:
      app: hister
  template:
    metadata:
      labels:
        app: hister
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: fix-data-permissions
          image: harbor.andreybondarenko.com/dockerhub/busybox:1.37
          command: ["sh", "-c", "chown -R 65532:65532 /data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: hister-data
              mountPath: /data
      containers:
        - name: hister
          image: harbor.andreybondarenko.com/github/asciimoo/hister:master
          imagePullPolicy: Always
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: HISTER__SERVER__ADDRESS
              value: 0.0.0.0:8080
            - name: HISTER__SERVER__BASE_URL
              value: "https://hister.andreybondarenko.com/"
            - name: HISTER_CONFIG
              value: /data/config.yml
            - name: HISTER_DATA_DIR
              value: /data
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: hister-data
              mountPath: /data
            - name: hister-config
              mountPath: /data/config.yml
              subPath: config.yml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 50m
              memory: 2256Mi
            limits:
              memory: 12256Mi
      volumes:
        - name: hister-data
          persistentVolumeClaim:
            claimName: hister-data
        - name: hister-config
          secret:
            secretName: hister-access-token
            items:
              - key: config.yml
                path: config.yml
