apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hister-access-token
  namespace: hister
  labels:
    app.kubernetes.io/name: hister
    app.kubernetes.io/instance: hister
    app.kubernetes.io/part-of: hister
    app.kubernetes.io/managed-by: argo-cd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: hister-access-token
    creationPolicy: Owner
  data:
    - secretKey: access_token
      remoteRef:
        key: hister/access_token
        property: access_token
