apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hister-access-token
  namespace: hister
  labels:
    app.kubernetes.io/name: hister
    app.kubernetes.io/instance: hister
    app.kubernetes.io/part-of: hister
    app.kubernetes.io/managed-by: argo-cd
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: hister-access-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        access_token: "{{ .access_token }}"
        base_url: "https://hister.andreybondarenko.com/{{ .url_secret }}/"
  data:
    - secretKey: access_token
      remoteRef:
        key: hister
        property: access_token
    - secretKey: url_secret
      remoteRef:
        key: hister
        property: secret
