apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hister-data
  namespace: hister
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-c: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
