---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-requests
  namespace: open-terminal
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 128Mi
      default:
        memory: 1Gi
      min:
        cpu: 5m
        memory: 32Mi
      max:
        memory: 2Gi
