---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: open-terminal
spec:
  hard:
    pods: "5"
    services: "5"
    secrets: "20"
    configmaps: "20"
    persistentvolumeclaims: "4"
    requests.storage: 25Gi
