---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: open-terminal
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
stringData:
  token: placeholder
