apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: open-terminal
  labels:
    app.kubernetes.io/name: open-terminal
    app.kubernetes.io/instance: open-terminal
    app.kubernetes.io/part-of: open-terminal
    app.kubernetes.io/managed-by: argo-cd
type: Opaque
stringData:
  token: bootstrap-placeholder
