apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-oidc-secret
  namespace: mastodon
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store-mastodon
    kind: SecretStore
  target:
    name: mastodon-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: mastodon
        property: OIDC_CLIENT_SECRET
