apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-redis
  namespace: mastodon
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store-redis
    kind: SecretStore
  target:
    name: mastodon-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis
        property: redis-password
