---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookmarked-media-sync
  namespace: mastodon
  labels:
    app.kubernetes.io/name: bookmarked-media-sync
    app.kubernetes.io/instance: bookmarked-media-sync
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/managed-by: argoCD
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store-immich-token
    kind: ClusterSecretStore
  target:
    name: bookmarked-media-sync
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: immich
        property: api_key
