---
image:
  repository: harbor.andreybondarenko.com/github/mastodon/mastodon
  tag: v4.5.10
  pullPolicy: IfNotPresent

mastodon:
  locale: en
  localDomain: mastodon.andreybondarenko.com
  webDomain: mastodon.andreybondarenko.com
  singleUserMode: false
  authorizedFetch: false
  limitedFederationMode: false

  createAdmin:
    enabled: false
    username: shaman007
    email: me@andreybondarenko.com

  hooks:
    dbPrepare:
      enabled: false
    dbMigrate:
      enabled: true
    deploySearch:
      enabled: false
    s3Upload:
      enabled: false

  secrets:
    existingSecret: mastodon
    existingSecretKeys:
      secretKeyBase: SECRET_KEY_BASE
      vapidPrivateKey: VAPID_PRIVATE_KEY
      vapidPublicKey: VAPID_PUBLIC_KEY
      arePrimaryKey: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
      areDeterministicKey: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
      areKeyDerivationSalt: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT

  web:
    replicas: 1
    port: 3000
    minThreads: "5"
    maxThreads: "5"
    workers: "2"
    persistentTimeout: "20"
    image:
      repository: harbor.andreybondarenko.com/github/mastodon/mastodon
      tag: v4.5.10
    resources:
      limits:
        memory: 4115Mi
      requests:
        cpu: 200m
        memory: 128Mi
    extraEnvVars:
      ALLOW_UNSAFE_AUTH_PROVIDER_REATTACH: "true"

  sidekiq:
    resources:
      limits:
        memory: 2052Mi
      requests:
        cpu: 75m
        memory: 1024Mi
    workers:
      - name: all-queues
        replicas: 1
        concurrency: 25
        queues:
          - default,8
          - push,6
          - ingress,4
          - mailers,2
          - pull
          - fasp
          - scheduler
        image:
          repository: harbor.andreybondarenko.com/github/mastodon/mastodon
          tag: v4.5.10
    extraEnvVars:
      ALLOW_UNSAFE_AUTH_PROVIDER_REATTACH: "true"

  streaming:
    replicas: 1
    port: 4000
    workers: 1
    baseUrl: null
    image:
      repository: harbor.andreybondarenko.com/github/mastodon/mastodon-streaming
      tag: v4.5.10
    resources:
      limits:
        memory: 110Mi
      requests:
        cpu: 37m
        memory: 110Mi
    extraEnvVars:
      ALLOW_UNSAFE_AUTH_PROVIDER_REATTACH: "true"

  s3:
    enabled: true
    existingSecret: mastodon
    existingSecretKeys:
      accessKeyId: AWS_ACCESS_KEY_ID
      secretAccessKey: AWS_SECRET_ACCESS_KEY
    bucket: mastodon
    endpoint: https://s3.andreybondarenko.com
    hostname: s3.andreybondarenko.com
    region: ""
    permission: ""
    aliasHost: s3.andreybondarenko.com/mastodon

  smtp:
    authMethod: plain
    caFile: /etc/ssl/certs/ca-certificates.crt
    deliveryMethod: smtp
    domain: andreybondarenko.com
    enableStartTls: auto
    fromAddress: notifications@andreybondarenko.com
    returnPath: notifications@andreybondarenko.com
    opensslVerifyMode: peer
    port: 25
    replyTo: me@andreybondarenko.com
    server: andreybondarenko.com
    tls: false
    existingSecret: mail
    existingSecretKeys:
      username: login
      password: password

  metrics:
    prometheus:
      enabled: true
      port: 9394
      web:
        detailed: false
      sidekiq:
        detailed: false

ingress:
  enabled: false

httproute:
  enabled: false

postgresql:
  hostname: mastodon-postgres.mastodon.svc.cluster.local
  port: 5432
  database: mastodon_production
  username: postgres
  existingSecret: postgres-password
  existingSecretKeys:
    username: username
    password: password
  preparedStatements: true
  direct:
    hostname: mastodon-postgres.mastodon.svc.cluster.local
    port: 5432
    database: mastodon_production

redis:
  hostname: redis.mastodon.svc.cluster.local
  port: 6379

elasticsearch:
  enabled: false
  hostname: es-es-http.elastic-stack.svc.cluster.local
  port: 9200
  tls: false
  username: elastic
  existingSecret: elasticsearch-password
  existingSecretKeys:
    username: username
    password: password

externalAuth:
  oidc:
    enabled: true
    displayName: Login via SSO
    issuer: https://sso.andreybondarenko.com/realms/master
    discovery: true
    scope: openid,email,profile
    uidField: uid
    clientId: mastodon
    clientSecret: ""
    existingSecret: mastodon-oidc-secret
    existingSecretKeys:
      clientId: OIDC_CLIENT_ID
      clientSecret: OIDC_CLIENT_SECRET
    redirectUri: https://mastodon.andreybondarenko.com/auth/auth/openid_connect/callback
    assumeEmailIsVerified: true
  oauthGlobal:
    omniauthOnly: false
  saml:
    enabled: false
  cas:
    enabled: false
  pam:
    enabled: false
  ldap:
    enabled: false

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 991
  runAsGroup: 991
  fsGroup: 991
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

deploymentAnnotations:
  configmap.reloader.stakater.com/auto: "true"

revisionPodAnnotation: true

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 100Mi

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
