---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mastodon-bookmarked-media-sync-allow-egress-kube-api
  namespace: mastodon
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: bookmarked-media-sync
  policyTypes:
    - Egress
  egress:
    - {}
