---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store-immich-token
  labels:
    app.kubernetes.io/name: bookmarked-media-sync
    app.kubernetes.io/instance: bookmarked-media-sync
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/managed-by: argoCD
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: immich
