---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookmarked-media-sync
  namespace: mastodon
  labels:
    app.kubernetes.io/name: bookmarked-media-sync
    app.kubernetes.io/instance: bookmarked-media-sync
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/managed-by: argoCD
automountServiceAccountToken: true
