{
 "title": "Keycloak Events",
 "tags": [ "keycloak" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Datasource", "query": "prometheus" },
   {
    "name": "realm",
    "label": "realm",
    "query": {
     "query": "label_values(keycloak_user_events_total{job=\"keycloak\"}, realm)"
    }
   },
   {
    "name": "client",
    "label": "client_id",
    "query": {
     "query": "label_values(keycloak_user_events_total{job=\"keycloak\",realm=~\"$realm\"}, client_id)"
    }
   },
   {
    "name": "event",
    "label": "event",
    "query": {
     "query": "label_values(keycloak_user_events_total{job=\"keycloak\",realm=~\"$realm\",client_id=~\"$client\"}, event)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Events rate by client/event",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (client_id,event) (rate(keycloak_user_events_total{job=\"keycloak\",realm=~\"$realm\",client_id=~\"$client\",event=~\"$event\"}[$__rate_interval]))",
     "legendFormat": "{{client_id}} / {{event}}"
    }
   ]
  },
  {
   "title": "Top events (events/s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\r\n  15,\r\n  sum by (event) (\r\n    increase(\r\n      keycloak_user_events_total{\r\n        job=\"keycloak\",\r\n        realm=~\"${realm:regex}\",\r\n        client_id=~\"${client:regex}\"\r\n      }[$__range]\r\n    )\r\n  ) / $__range_s\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Top clients (events/s)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(\r\n  15,\r\n  sum by (client_id) (\r\n    increase(\r\n      keycloak_user_events_total{\r\n        job=\"keycloak\",\r\n        realm=~\"${realm:regex}\",\r\n        event=~\"${event:regex}\"\r\n      }[$__range]\r\n    )\r\n  ) / $__range_s\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Errors by client/event/error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (client_id,event) (\r\n  increase(keycloak_user_events_total{job=\"keycloak\"}[$__range])\r\n)\r\n",
     "legendFormat": "{{client_id}} / {{event}} / {{error}}"
    }
   ]
  }
 ]
}