{
 "title": "SeaweedFS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Filer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filer Request Duration 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Request Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {}
   ]
  },
  {
   "title": "Filer QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(SeaweedFS_filerStore_request_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Concurrent Uploads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SeaweedFS_filer_in_flight_upload_count",
     "legendFormat": "uploads"
    }
   ]
  },
  {
   "title": "Filer Concurrent Upload Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "SeaweedFS_filer_in_flight_upload_bytes",
     "legendFormat": "bytes"
    }
   ]
  },
  { "title": "S3 Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "S3 Request Duration 90th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_s3_request_seconds_bucket[1m])) by (le, type, bucket))",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Traffic Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_received_bytes_total[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Traffic Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_bucket_traffic_sent_bytes_total[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API Calls per Bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_s3_request_total[$__interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "S3 API QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(SeaweedFS_s3_request_total[1m])",
     "legendFormat": "{{bucket}} {{type}}"
    }
   ]
  },
  { "title": "Volume Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Volume Server Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[1m])) by (le, exported_instance))",
     "legendFormat": "{{exported_instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_volumeServer_request_seconds_bucket[1m])) by (le))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Volume Server QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_volumeServer_request_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "S3 Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(SeaweedFS_s3_bucket_size_bytes) by (bucket)",
     "legendFormat": "{{bucket}} (logical)"
    },
    {
     "expr": "max(SeaweedFS_s3_bucket_physical_size_bytes) by (bucket)",
     "legendFormat": "{{bucket}} (physical)"
    }
   ]
  },
  {
   "title": "S3 Bucket Object Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(SeaweedFS_s3_bucket_object_count) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_volumes) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_max_volumes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Collection and Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (collection, type)",
     "legendFormat": "{{collection}} {{type}}"
    },
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used Disk Space by Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(SeaweedFS_volumeServer_total_disk_size) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Filer Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Filer Store Request Duration 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(SeaweedFS_filerStore_request_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Filer Store QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(SeaweedFS_filerStore_request_total [1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Filer Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Filer Go Memory Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"seaweedfs-metrics-filer\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Filer Go GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Filer Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"seaweedfs-metrics-filer\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "resident {{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"seaweedfs-metrics-filer\"}",
     "legendFormat": "virtual {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"seaweedfs-metrics-filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "process_max_fds{job=\"seaweedfs-metrics-filer\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{exported_instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}