apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak-oidc-token-renewer
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: argoCD
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: keycloak-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: keyckoak
        property: admin-username
    - secretKey: password
      remoteRef:
        key: keyckoak
        property: admin-password
