---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
