apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: traefik-allow-egress-kube-apiserver
  namespace: traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  egress:
    - toEntities:
        - kube-apiserver
    - toServices:
        - k8sService:
            namespace: default
            serviceName: kubernetes
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
