---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nextcloud-lh
  namespace: nextcloud
  labels:
    app: mysql-nextcloud
    tier: mysql
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-b: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
