---
apiVersion: v1
kind: Service
metadata:
  namespace: nextcloud
  name: nextcloud-web
  labels:
    app: nextcloud
    component: web
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  clusterIP: None
  selector:
    app: nextcloud
    component: web
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: fastcgi
      protocol: TCP
      port: 9000
      targetPort: 9000
