---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-web
  namespace: nextcloud
  labels:
    app: nextcloud
    component: web
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
  annotations:
    configmap.reloader.stakater.com/auto: "true"
spec:
  serviceName: nextcloud-web
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: web
  template:
    metadata:
      labels:
        app: nextcloud
        component: web
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 993
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - w386.k8s.my.lan
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - photon
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: phpini
          configMap:
            name: php-fpm-config
        - name: nextcloud-config
          configMap:
            name: nextcloud-config
            items:
              - key: config
                path: nextcloud.conf
        - name: varrun
          emptyDir:
            sizeLimit: 10Mi
        - name: run
          emptyDir:
            sizeLimit: 10Mi
        - name: sessions
          emptyDir:
            sizeLimit: 10Mi
        - name: tmp
          emptyDir:
            sizeLimit: 1512Mi
        - name: nextcloud-lh
          persistentVolumeClaim:
            claimName: nextcloud-lh-120gi
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: alloy-config
          configMap:
            name: alloy-nextcloud-config
        - name: alloy-run
          emptyDir: {}
        - name: alloy-data
          emptyDir: {}
        - name: nginx-cache
          emptyDir:
            sizeLimit: 500Mi
      containers:
        - name: php-nextcloud
          image: harbor.andreybondarenko.com/library/php:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: phpini
              mountPath: /etc/php/8.4/fpm/pool.d/php.ini
              subPath: php.ini
            - name: phpini
              mountPath: /etc/php/8.4/fpm/php.ini
              subPath: php.ini
            - name: phpini
              mountPath: /etc/php/8.4/fpm/pool.d/www.conf
              subPath: www.conf
            - name: nextcloud-lh
              mountPath: /nextcloud
            - name: varrun
              mountPath: /var/run/php
            - name: sessions
              mountPath: /var/lib/php/sessions
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
            - name: dev-dri
              mountPath: /dev/dri
              readOnly: false
          ports:
            - containerPort: 9000
              name: fastcgi
          readinessProbe:
            tcpSocket:
              port: fastcgi
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: fastcgi
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add: ["SYS_ADMIN"]
          resources:
            requests:
              cpu: "27m"
              memory: "6306Mi"
            limits:
              memory: "6306Mi"
        - name: nextcloud-nginx
          image: harbor.andreybondarenko.com/dockerhub/nginx:1.29.6
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: nextcloud-lh
              mountPath: /nextcloud
            - name: nextcloud-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              memory: "100Mi"
        - name: alloy
          image: harbor.andreybondarenko.com/dockerhub/grafana/alloy:v1.14.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --server.http.listen-addr=0.0.0.0:12345
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          livenessProbe:
            tcpSocket:
              port: 12345
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "177m"
              memory: "107Mi"
            limits:
              memory: "107Mi"
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
              readOnly: true
            - name: alloy-run
              mountPath: /run/alloy
            - name: nextcloud-lh
              mountPath: /nextcloud
            - name: alloy-data
              mountPath: /data-alloy
