---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: nextcloud
spec:
  ports:
    - { name: redis, port: 6379, targetPort: redis }
    - { name: redis-exporter, port: 9121, targetPort: redis-exporter }
  selector: { app: valkey }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: nextcloud
  labels:
    &labels {
      app: valkey,
      app.kubernetes.io/name: valkey,
      app.kubernetes.io/instance: nextcloud-valkey,
    }
spec:
  serviceName: valkey
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    { whenDeleted: Retain, whenScaled: Retain }
  selector:
    matchLabels: { app: valkey }
  template:
    metadata:
      labels: *labels
    spec:
      priorityClassName: homelab-essential
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        {
          fsGroup: 999,
          fsGroupChangePolicy: OnRootMismatch,
          seccompProfile: { type: RuntimeDefault },
        }
      containers:
        - name: valkey
          image: harbor.andreybondarenko.com/dockerhub/valkey/valkey:9
          args: ["--appendonly", "yes", "--save", "60", "1"]
          ports: [{ name: redis, containerPort: 6379 }]
          readinessProbe:
            &probe {
              exec: { command: [valkey-cli, ping] },
              periodSeconds: 10,
              timeoutSeconds: 5,
            }
          livenessProbe: *probe
          volumeMounts: [{ name: data, mountPath: /data }]
          securityContext:
            &security {
              runAsUser: 999,
              runAsGroup: 999,
              runAsNonRoot: true,
              allowPrivilegeEscalation: false,
              capabilities: { drop: [ALL] },
              readOnlyRootFilesystem: true,
            }
          resources:
            { requests: { cpu: 40m, memory: 64Mi }, limits: { memory: 512Mi } }
        - name: redis-exporter
          image: harbor.andreybondarenko.com/dockerhub/oliver006/redis_exporter:v1.90.0
          env: [{ name: REDIS_ADDR, value: "redis://localhost:6379" }]
          ports: [{ name: redis-exporter, containerPort: 9121 }]
          securityContext: *security
          resources:
            { requests: { cpu: 10m, memory: 64Mi }, limits: { memory: 64Mi } }
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        {
          accessModes: [ReadWriteOnce],
          storageClassName: longhorn,
          resources: { requests: { storage: 1Gi } },
        }
