apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-report-ui
  namespace: ca-scanner
  labels:
    app.kubernetes.io/name: ca-report-ui
    app.kubernetes.io/instance: ca-report-ui
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-report-ui
  template:
    metadata:
      labels:
        app: ca-report-ui
    spec:
      priorityClassName: homelab-best-effort
      serviceAccountName: ca-scanner
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: ui
          image: harbor.andreybondarenko.com/library/canitiser:2026-07-31-022908
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/ca-report-server.py"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 100
            seccompProfile:
              type: RuntimeDefault
          env:
            # use "all" to show all namespaces, or "ca-scanner" to show only that ns
            - name: REPORT_NAMESPACE
              value: "ca-scanner"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              memory: 96Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ca-report-ui
  namespace: ca-scanner
spec:
  selector:
    app: ca-report-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
