---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
    app.kubernetes.io/name: immich-server
    app.kubernetes.io/instance: immich-server
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/version: v2.4.1
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
        app.kubernetes.io/name: immich-server
        app.kubernetes.io/part-of: immich
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: w386.k8s.my.lan
      containers:
        - name: immich-server
          image: harbor.andreybondarenko.com/github/immich-app/immich-server:v2.4.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-env
                  key: DB_PASSWORD
            - name: REDIS_HOSTNAME
              value: immich-valkey
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: TZ
              value: Europe/Prague
          ports:
            - name: http
              containerPort: 2283
          startupProbe:
            httpGet:
              path: /api/server/ping
              port: http
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            periodSeconds: 10
          volumeMounts:
            - name: library
              mountPath: /data
            - name: stash-data
              mountPath: /external-libraries/stash-data
              readOnly: true
          resources:
            requests:
              cpu: 250m
              memory: 4Gi
            limits:
              memory: 48Gi
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library-lh
        - name: stash-data
          hostPath:
            path: /storage/k8s/stash-data
            type: Directory
