---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
    app.kubernetes.io/name: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/version: v2.6.3
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
        app.kubernetes.io/name: immich-machine-learning
        app.kubernetes.io/part-of: immich
    spec:
      priorityClassName: homelab-essential
      runtimeClassName: nvidia
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: talos-d4h-k5m
      containers:
        - name: immich-machine-learning
          image: harbor.andreybondarenko.com/github/immich-app/immich-machine-learning:v3.0.3-cuda
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-env
                  key: DB_PASSWORD
            - name: REDIS_HOSTNAME
              value: immich-valkey
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: HF_XET_CACHE
              value: /cache/huggingface-xet
            - name: MPLCONFIGDIR
              value: /cache/matplotlib-config
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: TZ
              value: Europe/Prague
          ports:
            - name: http
              containerPort: 3003
          startupProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: cache
              mountPath: /cache
          resources:
            requests:
              cpu: 50m
              memory: 2304Mi
            limits:
              memory: 4352Mi
              nvidia.com/gpu: 1
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: immich-ml-cache-lh
