---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-vision-tagging
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-vision-tagging
    app.kubernetes.io/instance: immich-vision-tagging
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argoCD
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: immich-vision-tagging
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: immich
        property: api_key
