---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-env
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argo-cd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: immich-env
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich
        property: db_password
