---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-immich-postgres-lh
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-postgres
    app.kubernetes.io/instance: immich-postgres
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
