---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-hdd
  labels:
    app: immich-server
    storage-role: immich-library
    app.kubernetes.io/name: immich-server
    app.kubernetes.io/instance: immich-server
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argoCD
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/mnt/storage/k8s/immich
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-d4h-k5m
