---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-lh
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-machine-learning
    app.kubernetes.io/instance: immich-machine-learning
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argoCD
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-c: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
