apiVersion: apps/v1
kind: Deployment
metadata:
  name: photon
  namespace: dawarich
  labels:
    app: photon
    app.kubernetes.io/name: photon
    app.kubernetes.io/instance: photon
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: photon
  template:
    metadata:
      labels:
        app: photon
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: photon
          image: harbor.andreybondarenko.com/github/rtuszik/photon-docker:v2.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: UPDATE_STRATEGY
              value: SEQUENTIAL
            - name: UPDATE_INTERVAL
              value: 720h
          ports:
            - containerPort: 2322
          startupProbe:
            httpGet:
              path: /status
              port: 2322
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2160
          readinessProbe:
            httpGet:
              path: /status
              port: 2322
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: 2322
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: photon-data
              mountPath: /photon/data
          resources:
            requests:
              memory: "1545Mi"
              cpu: "10m"
            limits:
              memory: "1545Mi"
      volumes:
        - name: photon-data
          persistentVolumeClaim:
            claimName: photon-data
