---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bastioncam
  namespace: bastioncam
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-internal-clients-only@kubernetescrd,traefik-robots-disallow-all@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - bastioncam.w386.k8s.my.lan
      secretName: bastioncam-vault-acme-tls
  rules:
    - host: bastioncam.w386.k8s.my.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bastioncam
                port: {name: http}
