---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bastioncam-data
  namespace: bastioncam
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-c: enabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
