{
 "title": "Cluster load",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Load average 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{kubernetes_node=~\".+\"} - node_memory_MemFree_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load5{kubernetes_node=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{kubernetes_node=~\".+\"} - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average 15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_load15{kubernetes_node=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{kubernetes_node=~\".+\",mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes transmit per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{kubernetes_node=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}