---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-requests
  namespace: nvidia-device-plugin
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      default:
        memory: 512Mi
      min:
        cpu: 5m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 1Gi
