---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 2.9.0
    chart: external-secrets
    helm:
      values: |
        global:
          repository: ghcr.io/external-secrets/external-secrets
        priorityClassName: homelab-critical
        webhook:
          priorityClassName: homelab-critical
          nodeSelector:
            kubernetes.io/hostname: w386
        certController:
          priorityClassName: homelab-critical
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - ServerSideApply=true
