---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v26.3.3
    chart: gpu-operator
    helm:
      values: |
        operator:
          repository: harbor.andreybondarenko.com/nvidia/nvidia
          resources:
            limits:
              memory: 350Mi
            requests:
              cpu: 200m
              memory: 100Mi
        validator:
          repository: harbor.andreybondarenko.com/nvidia/nvidia
        driver:
          enabled: false
        toolkit:
          enabled: false
        hostPaths:
          driverInstallDir: /usr/local
        devicePlugin:
          repository: harbor.andreybondarenko.com/nvidia/nvidia
          config:
            create: true
            name: nvidia-device-plugin-config
            default: default
            data:
              default: |-
                version: v1
                flags:
                  migStrategy: none
                  failOnInitError: true
                  nvidiaDriverRoot: /
                  plugin:
                    deviceListStrategy: envvar
                    deviceIDStrategy: uuid
                sharing:
                  timeSlicing:
                    resources:
                      - name: nvidia.com/gpu
                        replicas: 8
        dcgmExporter:
          repository: harbor.andreybondarenko.com/nvidia/nvidia/k8s
        gfd:
          repository: harbor.andreybondarenko.com/nvidia/nvidia
        migManager:
          repository: harbor.andreybondarenko.com/nvidia/nvidia/cloud-native
        node-feature-discovery:
          image:
            repository: harbor.andreybondarenko.com/k8s/nfd/node-feature-discovery
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
