---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: access-management
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: access-management
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cross-namespace read-only access and identity resources
  sourceRepos:
    - https://github.com/shaman007/home-k3s.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cilium-secrets
    - server: https://kubernetes.default.svc
      namespace: external-secrets
    - server: https://kubernetes.default.svc
      namespace: gpu-operator
    - server: https://kubernetes.default.svc
      namespace: harbor
    - server: https://kubernetes.default.svc
      namespace: headlamp
    - server: https://kubernetes.default.svc
      namespace: kube-node-lease
    - server: https://kubernetes.default.svc
      namespace: kube-public
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: lenka
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: metallb-system
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: opensearch
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: vault
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  orphanedResources:
    warn: true
