---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-builder
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: image-builder
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: image-builder
  syncPolicy:
    automated: {}
