---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v26.3.3
    chart: gpu-operator
    helm:
      values: |
        driver:
          enabled: false
        toolkit:
          enabled: false
        hostPaths:
          driverInstallDir: /usr/local
        devicePlugin:
          config:
            create: true
            name: nvidia-device-plugin-config
            default: default
            data:
              default: |-
                version: v1
                flags:
                  migStrategy: none
                  failOnInitError: true
                  nvidiaDriverRoot: /
                  plugin:
                    deviceListStrategy: envvar
                    deviceIDStrategy: uuid
                sharing:
                  timeSlicing:
                    resources:
                      - name: nvidia.com/gpu
                        replicas: 8
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
  syncPolicy:
    automated:
      enabled: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
