---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: minecraft
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minecraft
  syncPolicy:
    automated:
      selfHeal: true
