apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nllb
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/shaman007/home-k3s.git
    path: nllb
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: nllb
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: latest
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
    syncOptions:
      - CreateNamespace=true
