---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.34.0
    helm:
      parameters:
        - name: global.tlsDisable
          value: 'false'
        - name: injector.enabled
          value: 'false'
        - name: server.ha.enabled
          value: 'true'
        - name: server.ha.raft.enabled
          value: 'true'
        - name: server.ha.replicas
          value: '2'
      values: |
        global:
          tlsDisable: false
        server:
          priorityClassName: homelab-critical
          extraEnvironmentVars:
            VAULT_CACERT: /vault/userconfig/vault-server-tls/ca.crt
          extraVolumes:
            - type: secret
              name: vault-server-tls
          affinity: |
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: vault
                      app.kubernetes.io/name: vault
                      component: server
                  topologyKey: kubernetes.io/hostname
          includeConfigAnnotation: true
          ha:
            apiAddr: "https://vault-active.vault.svc:8200"
            raft:
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 0
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
                  tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
                  telemetry {
                    unauthenticated_metrics_access = "true"
                  }
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}

                telemetry {
                  prometheus_retention_time = "2m"
                  disable_hostname = true
                }
        csi:
          priorityClassName: homelab-critical
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated: {}
