---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 2.2.15
    helm:
      values: |
        image:
          repository: harbor.andreybondarenko.com/github/stakater/reloader
        reloader:
          autoReloadAll: false
          reloadStrategy: annotations
          readOnlyRootFileSystem: true
          deployment:
            priorityClassName: homelab-critical
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
