---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: workloads
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: wordpress
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: wordpress-daily-report-metrics
      namespace: wordpress
      jsonPointers:
        - /data/metrics.prom
        - /data/report.txt
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
