---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 3.5.0
    chart: eck-operator
    helm:
      releaseName: eck-operator
      values: |
        priorityClassName: homelab-critical
        image:
          repository: harbor.andreybondarenko.com/elastic/eck/eck-operator
        resources:
          requests:
            cpu: 25m
            memory: 150Mi
          limits:
            memory: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated:
      selfHeal: true
