---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  finalizers:
    - pre-delete-finalizer.argocd.argoproj.io
    - pre-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.11.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          persistence:
            defaultClassReplicaCount: 1
            defaultDataLocality: best-effort
            recurringJobSelector:
              enable: true
              jobList: '[{"name":"trim-daily-a","isGroup":false}]'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
