---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-mail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts/
    targetRevision: 0.16.9
    chart: redis
    helm:
      releaseName: redis
      values: |
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
        redisExporter:
          enabled: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
      parameters:
      - name: redisExporter.enabled
        value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mail
  syncPolicy:
    automated: {}
