---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: 'https://charts.external-secrets.io'
    targetRevision: 2.9.0
    chart: external-secrets
    helm:
      values: |
        global:
          repository: ghcr.io/external-secrets/external-secrets
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              matchLabelKeys:
                - pod-template-hash
        replicaCount: 3
        leaderElect: true
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        podDisruptionBudget:
          enabled: true
          minAvailable: 2
        priorityClassName: homelab-critical
        webhook:
          replicaCount: 3
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 0
              maxUnavailable: 1
          priorityClassName: homelab-critical
          podDisruptionBudget:
            enabled: true
            minAvailable: 2
        certController:
          replicaCount: 3
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxSurge: 0
              maxUnavailable: 1
          priorityClassName: homelab-critical
          podDisruptionBudget:
            enabled: true
            minAvailable: 2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true
    syncOptions:
      - ServerSideApply=true
