---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-network-policy
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: openbao
    targetRevision: main
    directory:
      recurse: false
      include: "network-policy-*.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
