---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.18.2
    chart: harbor
    helm:
      values: |
        core:
          resources:
            requests:
              memory: 213Mi
              cpu: 10m
            limits:
              memory: 213Mi
        database:
          internal:
            resources:
              requests:
                memory: 1250Mi
                cpu: 10m
              limits:
                memory: 1250Mi
        exporter:
          replicas: 1
        jobservice:
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 100Mi
        nginx:
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 100Mi
        portal:
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 100Mi
        redis:
          internal:
            resources:
              requests:
                memory: 113Mi
                cpu: 10m
              limits:
                memory: 113Mi
        registry:
          registry:
            resources:
              requests:
                memory: 256Mi
                cpu: 124m
              limits:
                memory: 512Mi
          controller:
            resources:
              requests:
                memory: 100Mi
                cpu: 10m
              limits:
                memory: 100Mi
        trivy:
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              cpu: null
              memory: 2Gi
        notary:
          enabled: false
        metrics:
          enabled: true
          core:
            path: /metrics
            port: 8001
          registry:
            path: /metrics
            port: 8001
          jobservice:
            path: /metrics
            port: 8001
          exporter:
            path: /metrics
            port: 8001
        persistence:
          enabled: true
          resourcePolicy: keep
          persistentVolumeClaim:
            registry:
              existingClaim: harbor-registry
        externalURL: https://harbor.andreybondarenko.com
        harborAdminPassword: Harbor12345
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: harbor
  ignoreDifferences:
  - group: ""
    kind: Secret
    jqPathExpressions:
    - .data
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .spec.template.metadata.annotations."checksum/secret"
    - .spec.template.metadata.annotations."checksum/secret-core"
    - .spec.template.metadata.annotations."checksum/secret-jobservice"
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
