---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comfyui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: comfyui
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: comfyui
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
