---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs-check
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: metrics
    targetRevision: HEAD
    directory:
      recurse: false
      include: "{cilium-network-policy-monitoring-allow-logs-check-kube-apiserver.yaml,config-map-logs-check-report.yaml,config-map-logs-check-scripts.yaml,cron-job-logs-check.yaml,external-secret-logs-check-grafana-token.yaml,network-policy-monitoring-allow-egress-logs-check-grafana.yaml,network-policy-monitoring-allow-egress-logs-check-kubernetes-api.yaml,network-policy-monitoring-allow-egress-logs-check-loki.yaml,network-policy-monitoring-allow-egress-logs-check-ollama.yaml,network-policy-monitoring-allow-egress-logs-check-smtp.yaml,role-binding-logs-check.yaml,role-logs-check.yaml,service-account-logs-check.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: logs-check-report
      namespace: monitoring
      jsonPointers:
        - /data/report.txt
        - /data/report.json
  syncPolicy:
    automated: {}
