---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system-network-policy
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: elastic-system
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
