---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-terminal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: open-terminal
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-terminal
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vault-token
      namespace: open-terminal
      jsonPointers:
        - /data
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
