---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-wordpress
  namespace: argocd
spec:
  project: storage
  source:
    repoURL: https://github.com/shaman007/home-k3s.git
    targetRevision: main
    path: redis/retired/wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
