---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mastodon-custom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: mastodon
    targetRevision: HEAD
    directory:
      recurse: false
      include: "{config-map-*.yaml,cron-job-*.yaml,external-secret-*.yaml,ingress-*.yaml,middleware-*.yaml,network-policy-*.yaml,persistent-volume-claim-data-mastodon-postgres-lh.yaml,role-*.yaml,role-binding-*.yaml,secret-store-*.yaml,service-account-*.yaml,service-mastodon-postgres*.yaml,stateful-set-mastodon-postgres.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mastodon
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
