---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-access-analytics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: metrics
    targetRevision: HEAD
    directory:
      recurse: false
      include: "{cluster-role-binding-external-access-daily-report.yaml,cluster-role-external-access-daily-report.yaml,config-map-external-access-analytics-exporter.yaml,config-map-external-access-daily-report-metrics.yaml,config-map-external-access-daily-report-scripts.yaml,cron-job-external-access-daily-report.yaml,deployment-external-access-analytics-exporter.yaml,role-binding-external-access-daily-report.yaml,role-external-access-daily-report.yaml,service-account-external-access-daily-report.yaml,service-external-access-analytics-exporter.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
