---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-ticker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: metrics
    targetRevision: HEAD
    directory:
      recurse: false
      include: "{config-map-finance-ticker-collector-scripts.yaml,config-map-finance-ticker-collector.yaml,config-map-finance-ticker-exporter.yaml,cron-job-finance-ticker-collector.yaml,deployment-finance-ticker-exporter.yaml,network-policy-monitoring-allow-egress-finance-ticker-collector-https.yaml,network-policy-monitoring-allow-egress-finance-ticker-collector-kubernetes-api.yaml,role-binding-finance-ticker-collector.yaml,role-finance-ticker-collector.yaml,service-account-finance-ticker-collector.yaml,service-finance-ticker-exporter.yaml}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: finance-ticker-metrics
      namespace: monitoring
      jsonPointers:
        - /data/report.txt
        - /data/metrics.prom
  syncPolicy:
    automated: {}
