apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-backup
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: talos-backup
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: talos-backup
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
