---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wordpress
  name: nginx-config
  labels:
    component: web
    app: wordpress
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
data:
  config: |
    map $http_geoip_country_code $country_code {
      default $http_geoip_country_code;
      "" $http_cf_ipcountry;
    }

    log_format blog_json escape=json '{'
                                 '"time_iso8601":"$time_iso8601",'
                                 '"remote_addr":"$remote_addr",'
                                 '"x_forwarded_for":"$http_x_forwarded_for",'
                                 '"cf_connecting_ip":"$http_cf_connecting_ip",'
                                 '"geoip_country":"$http_geoip_country",'
                                 '"geoip_country_code":"$http_geoip_country_code",'
                                 '"cf_ipcountry":"$country_code",'
                                 '"remote_user":"$remote_user",'
                                 '"host":"$host",'
                                 '"method":"$request_method",'
                                 '"request_uri":"$request_uri",'
                                 '"status":$status,'
                                 '"body_bytes_sent":$body_bytes_sent,'
                                 '"referer":"$http_referer",'
                                 '"user_agent":"$http_user_agent"'
                               '}';
    server {
      listen 8080;
      gzip on;
      index index.php index.html;
      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log blog_json;
      root /code;
      client_max_body_size 250M;
      add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
      location = /health {
          include fastcgi_params;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param SCRIPT_FILENAME /health;
          access_log off;
      }
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
      location  ~* ^.+\.(pdf|ovpn|svg|ico|odp|txt|xml|well-known)$ {
          #root /code;
          allow all;
      }
      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
