---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: wordpress-lh
  labels:
    storage.k8s.io/name: longhorn
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup-daily-retain31-a: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 3221225472 # 3Gi
