---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress-daily-report
  namespace: wordpress
  labels:
    app.kubernetes.io/name: wordpress-daily-report
    app.kubernetes.io/instance: wordpress-daily-report
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: argoCD
automountServiceAccountToken: true
