---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-le-tls
  namespace: traefik
  labels:
    app.kubernetes.io/name: sync-le-tls
    app.kubernetes.io/part-of: mail
    app.kubernetes.io/managed-by: argoCD
