apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-prod
  namespace: mail
  labels:
    app.kubernetes.io/name: letsencrypt-prod
    app.kubernetes.io/managed-by: argoCD
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
