apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vault-server-allow-egress-kube-api
  namespace: vault
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: vault
      k8s:app.kubernetes.io/name: vault
      k8s:component: server
  egress:
    - toEntities:
        - kube-apiserver
    - toServices:
        - k8sService:
            namespace: default
            serviceName: kubernetes
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
