apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-token-rotator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["external-secrets.io"]
    resources: ["secretstores", "clustersecretstores"]
    verbs: ["get", "list"]
