apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-allow-egress-kube-api
  namespace: vault
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow access to the Kubernetes API service ClusterIP for service registration.
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443
    # Allow access to the current control-plane endpoint in case egress is enforced post-DNAT.
    - to:
        - ipBlock:
            cidr: 192.168.1.209/32
      ports:
        - protocol: TCP
          port: 6443
