apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-pki-renewer
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-server-tls"]
    verbs: ["get", "update", "patch"]
