---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-requests
  namespace: comfyui
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 512Mi
      default:
        memory: 8Gi
      min:
        cpu: 25m
        memory: 128Mi
      max:
        memory: 16Gi
