apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-data
  namespace: comfyui
  labels:
    app: comfyui
    app.kubernetes.io/name: comfyui
    app.kubernetes.io/instance: comfyui
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
