---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: podman-builder
  namespace: image-builder
  labels:
    app.kubernetes.io/name: podman-builder
    app.kubernetes.io/instance: podman-builder
    app.kubernetes.io/managed-by: argoCD
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: podman-builder-harbor
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: harbor
        property: user
    - secretKey: password
      remoteRef:
        key: harbor
        property: password
