---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: image-builder
  annotations:
    vault.w386.k8s.my.lan/token-policies: harbor
  labels:
    app.kubernetes.io/name: podman-builder
    app.kubernetes.io/instance: podman-builder
    app.kubernetes.io/managed-by: argoCD
spec:
  refreshInterval: 900
  provider:
    vault:
      server: http://vault.vault.svc:8200
      path: kv
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token-image-builder
          key: token
