apiVersion: v1
kind: ConfigMap
metadata:
  name: ripe-atlas-settings
  namespace: ripe-atlas
  labels:
    app.kubernetes.io/name: ripe-atlas
    app.kubernetes.io/instance: ripe-atlas
    app.kubernetes.io/managed-by: argoCD
data:
  config.txt: |
    RXTXRPT=yes
