apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ripe-atlas-config
  namespace: ripe-atlas
  labels:
    app.kubernetes.io/name: ripe-atlas
    app.kubernetes.io/instance: ripe-atlas
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ripe-atlas-spool
  namespace: ripe-atlas
  labels:
    app.kubernetes.io/name: ripe-atlas
    app.kubernetes.io/instance: ripe-atlas
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
