apiVersion: v2
appVersion: v4.5.9
description: 'Mastodon is a free, open-source social network server based on ActivityPub. '
home: https://joinmastodon.org
icon: https://avatars.githubusercontent.com/u/24979032
maintainers:
- name: Mastodon
  url: https://joinmastodon.org
name: mastodon
type: application
version: 0.4.1
