---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minecraft
  name: minecraft1-lh
  labels:
    storage.k8s.io/name: longhorn
    tier: backend
    app: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup-daily-retain31-c: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10737418240
