---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-requests
  namespace: ollama
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 512Mi
