{{- if .Values.redis.sidekiq.enabled }}
{{- if and (not .Values.redis.sidekiq.existingSecret) .Values.redis.sidekiq.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mastodon.secrets.redisSidekiqName" . }}
  labels:
    {{- include "mastodon.labels" . | trim | nindent 4 }}
    {{- include "mastodon.userLabels" . | trim | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  password: {{ .Values.redis.sidekiq.password | b64enc }}
{{- end }}
{{- end }}
