apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
  labels:
    app.kubernetes.io/name: stirling-pdf
    app.kubernetes.io/instance: stirling-pdf
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      priorityClassName: homelab-best-effort
      containers:
        - name: stirling-pdf
          image: harbor.andreybondarenko.com/dockerhub/stirlingtools/stirling-pdf:2.14.3-fat
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: HOME
              value: /home/stirlingpdfuser
          ports:
            - containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: configs
              mountPath: /configs
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /logs
            - name: custom-files
              mountPath: /customFiles
            - name: pipeline
              mountPath: /pipeline
            - name: storage
              mountPath: /storage
            - name: home
              mountPath: /home/stirlingpdfuser
            - name: local-bin
              mountPath: /usr/local/bin
          resources:
            requests:
              memory: 1344Mi
            limits:
              memory: 1920Mi
      volumes:
        - name: configs
          persistentVolumeClaim:
            claimName: stirling-pdf-configs
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: custom-files
          emptyDir: {}
        - name: pipeline
          emptyDir: {}
        - name: storage
          emptyDir: {}
        - name: home
          emptyDir: {}
        - name: local-bin
          emptyDir: {}
