---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-tls
  namespace: mail
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: mail-tls
  dnsNames:
    - andreybondarenko.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
