---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-mail-lh
  namespace: mail
  labels:
    app: valkey
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: mail-valkey
    app.kubernetes.io/managed-by: argoCD
    storage.k8s.io/name: longhorn
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/backup-daily-retain31-c: enabled
    recurring-job.longhorn.io/trim-daily-c: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
