---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-rsync-authorized-keys
  namespace: backup-rsync
data:
  authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXDgbz5nhbtyeYSn3QVBKSx5GkxmRMuKddb3T4AqisxUArpf0c6gOKRREBQEfxcoGCwlCj2iKRnpaA2i3fBSNNCpt2U9p2pNeX6F4BgeSfnuwdkQoiBs6PB8TnhuA1blyN5aLHJcMke5sm9b6QkVh04ajXjUGQug7YWvbRbhrilUhOxCPfK6hKOod6fBIFVdMZT6QIFHNDqJHns4lbpnrBQs2jSSclgE2yxj9fOYWU2V6GXbDT/1uSDlToQrse5O4/RmHufAcWBVKlukaw8miHKTvNAjwyynW8014r6BOfVQ6BS1TbTd7EQ4N0G5DBATlILdzJzIup/mt1izZ/dz37 abondare@redhat.com
