---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-rsync
  namespace: backup-rsync
  labels:
    app: backup-rsync
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backup-rsync
  template:
    metadata:
      labels:
        app: backup-rsync
    spec:
      automountServiceAccountToken: false
      priorityClassName: homelab-essential
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - talos-d4h-k5m
      containers:
        - name: sshd
          image: harbor.andreybondarenko.com/quay/panubo/sshd:1.10.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SSH_USERS
              value: "backup:1000:1000"
            - name: RSYNC_MODE
              value: "true"
          ports:
            - containerPort: 22
              name: ssh
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: plex
              mountPath: /storage/k8s/plex
            - name: pictures
              mountPath: /storage/Pictures
            - name: stash-data
              mountPath: /storage/k8s/stash-data
              readOnly: true
            - name: immich
              mountPath: /storage/k8s/immich
              readOnly: true
            - name: authorized-keys
              mountPath: /etc/authorized_keys
              readOnly: true
            - name: host-keys
              mountPath: /etc/ssh/keys
      volumes:
        - name: plex
          hostPath:
            path: /var/mnt/storage/k8s/plex
            type: Directory
        - name: pictures
          hostPath:
            path: /var/mnt/storage/Pictures
            type: Directory
        - name: stash-data
          hostPath:
            path: /var/mnt/storage/k8s/stash-data
            type: Directory
        - name: immich
          hostPath:
            path: /var/mnt/storage/k8s/immich
            type: Directory
        - name: authorized-keys
          configMap:
            name: backup-rsync-authorized-keys
            defaultMode: 0444
        - name: host-keys
          persistentVolumeClaim:
            claimName: backup-rsync-host-keys
