---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-rsync-host-keys
  namespace: backup-rsync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Mi
