apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: karakeep-allow-egress-ollama
  namespace: karakeep
spec:
  podSelector:
    matchLabels:
      app: karakeep
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ollama
          podSelector:
            matchLabels:
              app: ollama
      ports:
        - protocol: TCP
          port: 11434
