---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  namespace: karakeep
  labels:
    app: karakeep
    app.kubernetes.io/name: karakeep
    app.kubernetes.io/instance: karakeep
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup-daily-retain30: enabled
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5368709120
