apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: convertx-env
  namespace: convertx
  labels:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/instance: convertx
    app.kubernetes.io/part-of: convertx
    app.kubernetes.io/managed-by: argo-cd
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: convertx-env
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: convertx
        property: jwt_token
