apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argo-cd
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: argocd-oidc-secret
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/managed-by: argo-cd
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd
        property: OIDC_CLIENT_SECRET
