apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: searxng
  labels:
    app: searxng
    app.kubernetes.io/name: searxng
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/managed-by: argoCD
spec:
  selector:
    app: searxng
  ports:
    - name: http
      port: 8080
      targetPort: http
