apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-data-local
  labels:
    app: stash
    app.kubernetes.io/name: stash
    app.kubernetes.io/instance: stash
    app.kubernetes.io/managed-by: argoCD
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /storage/k8s/stash-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - w386.k8s.my.lan
