apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stash
  name: stash-data-local
  labels:
    app: stash
    app.kubernetes.io/name: stash
    app.kubernetes.io/instance: stash
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Ti
