apiVersion: v1
kind: Service
metadata:
  name: stash
  namespace: stash
  labels:
    app: stash
    app.kubernetes.io/name: stash
    app.kubernetes.io/instance: stash
    app.kubernetes.io/managed-by: argoCD
spec:
  selector:
    app: stash
  ports:
    - name: http
      port: 9999
      targetPort: http
