apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stash
  namespace: stash
  labels:
    app: stash
    app.kubernetes.io/name: stash
    app.kubernetes.io/instance: stash
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  serviceName: stash-headless
  replicas: 1
  selector:
    matchLabels:
      app: stash
  template:
    metadata:
      labels:
        app: stash
    spec:
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: w386.k8s.my.lan
      containers:
        - name: stash
          image: stashapp/stash:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: STASH_STASH
              value: /data/
            - name: STASH_GENERATED
              value: /generated/
            - name: STASH_METADATA
              value: /metadata/
            - name: STASH_CACHE
              value: /cache/
            - name: STASH_PORT
              value: "9999"
          ports:
            - name: http
              containerPort: 9999
            - name: ai
              containerPort: 7800
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: stash-config-lh
              mountPath: /root/.stash
            - name: stash-data-local
              mountPath: /data
            - name: stash-metadata-lh
              mountPath: /metadata
            - name: stash-cache-lh
              mountPath: /cache
            - name: stash-blobs-lh
              mountPath: /blobs
            - name: stash-generated-lh
              mountPath: /generated
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: stash-config-lh
          persistentVolumeClaim:
            claimName: stash-config-lh
        - name: stash-data-local
          persistentVolumeClaim:
            claimName: stash-data-local
        - name: stash-metadata-lh
          persistentVolumeClaim:
            claimName: stash-metadata-lh
        - name: stash-cache-lh
          persistentVolumeClaim:
            claimName: stash-cache-lh
        - name: stash-blobs-lh
          persistentVolumeClaim:
            claimName: stash-blobs-lh
        - name: stash-generated-lh
          persistentVolumeClaim:
            claimName: stash-generated-lh
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
