apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-small-data
  namespace: ollama
  labels:
    app: ollama-small
    app.kubernetes.io/name: ollama-small
    app.kubernetes.io/instance: ollama-small
    app.kubernetes.io/part-of: ollama
    app.kubernetes.io/managed-by: argoCD
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
