apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: monitoring-allow-finance-ticker-collector-kube-apiserver
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app: finance-ticker-collector
  egress:
    - toEntities:
        - kube-apiserver
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
