---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-health-report
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-health-report
subjects:
  - kind: ServiceAccount
    name: platform-health-report
    namespace: monitoring
