---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-access-daily-report
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-access-daily-report
subjects:
  - kind: ServiceAccount
    name: external-access-daily-report
    namespace: monitoring
