---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: logs-check-grafana-token
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: logs-check-grafana-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: monitoring
        property: GRAFANA_TOKEN
