---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-health-report
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-health-report
subjects:
  - kind: ServiceAccount
    name: platform-health-report
    namespace: monitoring
