---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-health-report
  namespace: monitoring
  labels:
    app: platform-health-report
    app.kubernetes.io/name: platform-health-report
    app.kubernetes.io/instance: platform-health-report
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: argoCD
