---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-access-daily-report
  namespace: monitoring
  labels:
    app: external-access-daily-report
    app.kubernetes.io/name: external-access-daily-report
    app.kubernetes.io/instance: external-access-daily-report
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: argoCD
