---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-check
  namespace: monitoring
  labels:
    app: logs-check
    app.kubernetes.io/name: logs-check
    app.kubernetes.io/instance: logs-check
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: argoCD
