---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: finance-ticker-collector
  namespace: monitoring
  labels:
    app: finance-ticker-collector
    app.kubernetes.io/name: finance-ticker-collector
    app.kubernetes.io/instance: finance-ticker-collector
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: argoCD
